[package]
name = "axum-sea-orm-artists-app"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [".", "api", "service", "entity", "migration"]

[dependencies]
axum-example-api = { path = "api" }